### ISSUE TITLE
Unidecode Error utf-8

### ISSUE THREAD

**Issue by kenjihiraoka** [xtream1101/s3-concat#12]
Hi guys, I've tried using this lib and got an error:

![Screenshot from 2020-09-23 11-56-19](https://user-images.githubusercontent.com/31676903/94030278-04753a00-fd94-11ea-821c-3cffc36488ea.png)

I saw the code that generate it: [get_small_parts method](https://github.com/xtream1101/s3-concat/blob/master/s3_concat/multipart_upload_job.py#L106)

Looking better for this error, I found the root reason: files that are compressed in gzip format or another one will be an exception for this code. In my case, my files are gzip format and the turn around was using the gzip lib to read files.

**Comment by xtream1101** [comment]
Thank you for this use case. Did not think of this being used for compressed files. But after looking at the gzip docs and some quick testing it does seem to be fine to concat the contents of multiple gzip files.

I will look into implementing this.

**Comment by xtream1101** [comment]
@kenjihiraoka I am making an update for this now, just so you know the way this works, is it will take all the file contents in all the gzip'd files and put it all into a single files content. 
For example:
file1.txt.gz has the contents of 
`Foobar\n`
file2.txt.gz
`Hello World\n`

After they get concat'd together, when extracted, will contain just the contents:
`Foobar\nHello World\n`

The 2 files contents become a single file.
