### ISSUE TITLE
Option to delete/remove source files after concat operation

### ISSUE THREAD

**Issue by nicof38** [xtream1101/s3-concat#13]
Hello,

Are you planning to add an option to delete source files after successful concat operation ?

Thanks

**Comment by xtream1101** [comment]
Sorry for the _very_ late response. But this library will not support deleting of the files. This is so files are not deleted by accident.

To get a list of files that were processed though, you can access that var `all_files` of the class `S3Concat`

```python
job = S3Concat(... )
job.add_files(path_to_concat)

job.concat(...)

files_to_delete = job.all_files  # list of s3 keys that were added to be combined
```
