### ISSUE TITLE
change to add_file definition to use head_object instead of get_object

### ISSUE THREAD

**Issue by aguyyala-disco** [xtream1101/s3-concat#4]
Hi @xtream1101 ! 

Thanks for your work on this. It's really useful.

I see that [add_file definition](https://github.com/xtream1101/s3-concat/blob/master/s3_concat/__init__.py#L63) needs only `ContentLength` which should be present in metadata. We can simply make head_object call rather than get_object which is expensive.

> def add_file(self, key):
             resp = self.s3.get_object(Bucket=self.bucket, Key=key)
             self.all_files.append((key, resp['ContentLength']))

Is there a reason to use get_object instead of head_object?

**Comment by xtream1101** [comment]
No reason, just an oversight. Thank you for pointing this out! It has been fixed in version `0.1.8`
