### ISSUE TITLE
Random Retry failed batch error

### ISSUE THREAD

**Issue by cscetbon** [xtream1101/s3-concat#5]
I don't know how it can happen as I only have small files and there is only one thread, but somehow batches fail. here is the code I use 
```
job = S3Concat(s3_bucket, merged_csv, min_file_size=None)
job.add_files(path.join(prefix, "data"))
job.concat()
```
and not often but it happens to raise the error mentioned in the title. Here are the logs https://pastebin.com/raw/svSZ2sgu.

**Comment by xtream1101** [comment]
I just added a log that will help debug this in version `0.1.9`.  
Update and re run and this way we can see exactly what key it thinks does not exist in your bucket.
