### ISSUE TITLE
Could we introduce thread to concat more faster?

### ISSUE THREAD

**Issue by y-ken** [xtream1101/s3-concat#9]
Before this test, I excluded files of 5MB or less to exclude the process of downloading locally.
When the concat process was executed using the average 20MB file group, the result was about 1 file per minute. It is a calculation that 200 files are combined in 1 minute. It means 100GB processing takes 100 minutes.

I have a total 100GB of files per hour and I want to finish the merge within 20 minutes.
For that, I thought that it was necessary to perform parallel processing using threads.

![image](https://user-images.githubusercontent.com/1734549/90713656-c7271380-e2e0-11ea-92bb-b5f938f39634.png)

**Comment by y-ken** [comment]
The purpose can be achieved by executing threads in parallel from the outside.

**Comment by xtream1101** [comment]
I am glad you found a solution, but I am going to re-open since since this is something I should add to this tool. I have threading working well for files smaller then 5MB, but have not spent much time on optimizing for larger source files.

**Comment by y-ken** [comment]
Sounds good to hear. 👍 

## suggestion to switch current threading, too

From my point of view, it seems current local merge operation code uses `threading` library for thread.
`threading` is working under GIL. thus it does not much faster than "right" thread.
https://medium.com/practo-engineering/threading-vs-multiprocessing-in-python-7b57f224eadb

It means it could not use over 2 cores of CPU.

As the solution, we have choice to use "concurrent.futures" Package.
That have nice library as `ThreadPoolExecutor` or `ProcessPoolExecutor`
You can also try [asyncio](https://docs.python.jp/3/library/asyncio.html#module-asyncio) Module for API call.

If we can switch to use that performance optimization, it also results much faster for such a small files concatination.

**Comment by xtream1101** [comment]
The type of threads were fixed in a previous MR. There is now a `main_threads` argument that solves the original request. This is new in version 0.2.4
